#!/usr/bin/python2.7
# By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
# What is the 10001st prime number?
X = 994 # X is the counter of how many prime numbers I calculate
Y = 7873 # Y is the prime number of that itteration
list1 = []

def test(PN):
	
	for N in xrange(1,PN):
		if N == 1 or N == PN:
			continue
		if PN % N == 0:
			return False
	else:
		return True

while X <= 10001:
	if test(Y) == True:
		print X," : ",Y
		list1.append(Y)
		X += 1
	Y += 1

#print list1
