#!/usr/bin/python2.7
# By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
# What is the 10001st prime number?
X = 0

while X <= 101:
	while Y < X
		print(X)
		X += 1
