#!/usr/bin/python2.7

def test():
	return "Hello World"

print test()

connector = "-"
list1 = ['1','2','3','4','5','6','7','8','9']

def test2(param1,param2):
	x = param1.join(param2)
	return x

print test2(connector,list1)
