#!/usr/bin/python2.7

import time

time.time()
time.gmtime()
time.ctime()

#Var time now
timenow = time.time()
#Var 5 day difference
#3600 = 1 hour
#86400 = 1 day
#432000 = 5 days
difference = 60 * 60 * 24 * 5

timelater = timenow + difference


