#!/usr/bin/python2.7

import time

print time.time()
print time.gmtime()
print time.ctime()

#Var time now
timenow = time.time()
#Var 5 day difference
#3600 = 1 hour
#86400 = 1 day
#432000 = 5 days
difference = 60 * 60 * 24 * 5

timelater = timenow + difference

print timenow
print timelater
print time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(timenow))
