#!/usr/bin/python2.7
from gi.repository import Gtk

class MyWindow(Gtk.Window):
	def __init__(self):
		#Create window
		Gtk.Window.__init__(self, title="hello")
		#Create button (Toggle)
		self.button = Gtk.Button(label="Hello World")
		self.button.connect("clicked", self.on_button_clicked)
		self.add(self.button)
	def on_button_clicked(self, widget):
		print widget
		print "Hello world"

win = MyWindow()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
