#!/usr/bin/python2.7
from gi.repository import Gtk

class LabelWindow(Gtk.Window):
	def __init__(self):
		#Create window
		Gtk.Window.__init__(self, title="Label window")
		vbox = Gtk.VBox(spacing=1)
		self.add(vbox)
		
		
		# Label
		label = Gtk.Label()
		label.set_text("Label text")
		label.set_line_wrap(True)
		vbox.pack_start(label, True, True, 0)
		
		
		#Create button (Toggle)
		button = Gtk.Button(label="Hello World")
		button.connect("clicked", self.on_button_clicked, label)
		vbox.pack_start(button, True, True, 0)
		
	
	#Method that is called on button click
	def on_button_clicked(self, widget,label):
		print widget
		label.set_text("Hello Worldadsfasdafdadadafd")


win = LabelWindow()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
