#!/usr/bin/python2.7
from gi.repository import Gtk


global PopUp



class MyWindow(Gtk.Window):
	def __init__(self):
		#Create window
		Gtk.Window.__init__(self, title="hello")
		#window.connect("destroy", lambda w: gtk.main_quit())
		#Create button (Toggle)
		self.button = Gtk.Button(label="Hello World")
		self.button.connect("clicked", self.on_button_clicked)
		self.add(self.button)
	
	#Method that is called on button click
	def on_button_clicked(self, widget):
		global PopUp
		status = "Ran"
		PopUp = PopUp()
		PopUp.show_all()

class PopUp(Gtk.Window):
	def __init__(self):
		#Create window
		Gtk.Window.__init__(self, title="hello")
		print "Message"



win = MyWindow()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()




