#!/usr/bin/python2.7
from datetime import datetime

now = datetime.now()

print datetime.now()
print now.year
print now.month
print now.day

print '%s/%s/%s' % (now.month, now.day, now.year)
print '%s:%s:%s' % (now.hour, now.minute, now.second)

