#!/usr/bin/python2.7
#If statment operators
# ==, !=, <, >, <=, >=,
a,b = 0,1

if a == b:
	print("a = b")
if a != b:
	print("a != b")
if a == b and b > 1:
	print(True)

var = 'This is true' if a == b else 'this is not true'
print(var)

x = int(input("Enter a number"))

if x < 0:
	x = 0
	print('Negative changed to zero')
elif x == 0:
	print('Zero')
elif x == 1:
	print('Single')
else:
	print('More')
