#!/usr/bin/python2.7
#IndexId0,1,2,3,4,5,6,7,8, 9,10
list1 = [1,2,3,4,5,6,7,8,9,10,11]

print(list1[2])
#3
print(list1[-2])
#10

length = len(list1)
print(list1[length-4])
#8

print(list1[2:5])
#3, 4, 5

print(list1[2:8:2])
#3, 5, 7

list2 = [12,13,14]
list1.extend(list2)

print(list1)
#1 - 14

list1[5] = 11
print list1
#edit index 5 and make it 11

list1[5] = list1[5] * 2
print list1
#edit index 5 and times it by 2

list1.insert(5,12)
print list1
#add in 12 as the 5th index


del list1[5:7]
print list1
#delete index 5-7

list1.remove(9)
print list1
#remove the value 9 not index

list1.reverse()
#reverse the list
list1.append(0)
#add 0 onto the end of the list
print list1


list2 = [4,6,2,2,7,9,4,1]
list2s = sorted(list2)

print list2
print list2s

