#!/usr/bin/python2.7

class Person:
	def __init__(self,gender,name):
		self.gender = gender
		self.name = name
	def display(self, value):
		print("You're a ", self.gender ," and you're name is: ", self.name)
		print(value)
#encapsulisation both running same class but not interfering
rob = Person('Male','Rob')
joan = Person('Female','Joan')
rob.display(21)
joan.display(3)
