#!/usr/bin/python2.7

# Check length > 10 	Done
# Has uppercase		Y
# Has lowercase		N
# Has digit		N

A = lambda Y: Y.isupper()
B = lambda Y: Y.islower()
C = lambda Y: Y.isdigit()


def test(data):
	print ""
	print "Password:", data
	# Length test
	if len(data) < 10:
		print "To short"
		return False
	# Uppercase test
	for letter in data:
		if A(letter) == True:
			break
	else:
		print "No Uppercase characters"
		return False
	# Lowercase test
	for letter in data:
		if B(letter) == True:
			break
	else:
		print "No Lowercase characters"
		return False
	# Digit test
	for letter in data:
		if C(letter) == True:
			break
	else:
		print "No numbers"
		return False
	



test(u'A1213pokl')
test(u'basE73oonew')
test(u'asasasasasasasaas')
test(u'QWERTYqwerty')
test(u'123456123456')
test(u'QwErTy911poqqqq')
