#!/usr/bin/python2.7

#http://en.wikipedia.org/wiki/Primitive_root_modulo_n
#For example, if n = 14 then the elements of Znx are the congruence classes {1, 3, 5, 9, 11, 13};
#there are [phi](14) = 6 of them. Here is a table of their powers modulo 14

N = 14

# Get all of the numbers up to N
for X in range(1,N):
    print X
    # for each number create a list of their value ** power
    L = []
    for Y in range(1,N):
    #    L.append(Y)
        L.append(X**Y%N)
    # print each list
    print set(L)
