#!/usr/bin/python2.7
import random
import string
#print(random.random())
rrange = random.sample(range(25),20)
lrange = string.lowercase[:26]
anotherr = []
#random call on the list of letters
#print "".join(lrange)

for number in rrange:
	random.randint(0,10)
	print(lrange[number])
	anotherr += lrange[number]

print anotherr
print "".join(anotherr)

print rrange
print lrange



#list/array of letters = string

#www.openbookproject.net/pybiblio/practice

'''
generate a string of 20 random characters

Logic

26 possible characters
0-25 in range

'''

