#!/usr/bin/python2.7
#Some positive integers n have the property that the sum [ n + reverse(n) ] consists entirely of odd (decimal) digits.
#For instance, 36 + 63 = 99 and 409 + 904 = 1313.
#We will call such numbers reversible; so 36, 63, 409, and 904 are reversible.
#Leading zeroes are not allowed in either n or reverse(n).

#There are 120 reversible numbers below one-thousand.

#How many reversible numbers are there below one-billion (10**9)?

X = 1000

LST = list(range(0,X))


#def sieve(For, Rev):
#    # Remove leading zeros
#    if Rev[0] == 0:
#        return False
#

    # Remove sums that are not only odd didgits



for X in LST:
    X = str(X)
    Y = X[::-1]
    # sieve out bad ones
#    if sieve(X) == False:
#        LST.remove(X)
    try:
        LST.remove(int(Y))
    except:
        continue


print LST
print len(LST)
