#!/usr/bin/python2.7
# String
VAR = "Hello, world"
# Value to change
N = 13

# Solution One
import codecs
print codecs.encode(VAR, 'rot_13')

# Solution Two
ALPHA = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz"
# So I can search by the letter
D1 = {'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25}
D2 = {'a': 26, 'c': 28, 'b': 27, 'e': 30, 'd': 29, 'g': 32, 'f': 31, 'i': 34, 'h': 33, 'k': 36, 'j': 35, 'm': 38, 'l': 37, 'o': 40, 'n': 39, 'q': 42, 'p': 41, 's': 44, 'r': 43, 'u': 46, 't': 45, 'w': 48, 'v': 47, 'y': 50, 'x': 49, 'z': 51}

def encrot(STRY):
    L = []
    for X in STRY:
        if X.isalpha() == True:
            L.append(ALPHA[D1[X.lower()] + N])
        else:
            L.append(X)
    return "".join(L)

def decrot(STRY):
    L = []
    for X in STRY:
        if X.isalpha() == True:
            L.append(ALPHA[D2[X.lower()] - N])
        else:
            L.append(X)
    return "".join(L)

print encrot(VAR)

print decrot("uryyb, jbeyq")
