#!/usr/bin/python2.7

#Smallest multiple from the range of 1,20
#https://projecteuler.net/problem=5
X = 2520

#while Z != False
for R in range(1,10):
	if (X / float(R)) % 1 != 0:
		break
	else:
		print X
		#return X

