#!/usr/bin/python2.7

# A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
# (a*a) + (b*b) = (c*c)
#
# For example, 	3*3 + 4*4 = 5*5
#		  9 +  16 =  25
#
# There exists exactly one Pythagorean triplet for which a + b + c = 1000.
# Find the product abc.

# a + b = c (all squared)
# a < b < c

# A+B+C  = 100
# A +  B = 50
# 9 + 16 = 25

#L = [3,4]
#X = []
#Y = 0
#
#for N in L:
#	X.append(N * N)
#	Y += N * N
#print X
#print Y
import sys

A = 0
B = 0

X = 100

C = int(X * 0.5)

while (A + B) != C:
	print A, B, C, X
	while A < B:
		A += 1
		print A, B, C, X
		if (A + B) == C:
			print "True"
		if A > 100 or B > 100:
			print "Error"
			sys.exit()
	print "Test"
	B += 1
	A = 0

print "End"
print A, B, C, X
#A < B 
