#!/usr/bin/python2.7

# A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
# (a*a) + (b*b) = (c*c)
#
# For example, 	3*3 + 4*4 = 5*5
#		  9 +  16 =  25
#
# There exists exactly one Pythagorean triplet for which a + b + c = 1000.
# Find the product abc.

# a + b = c (all squared)
# a < b < c

# A+B+C  = 100
# A +  B = 50
# 9 + 16 = 25

#L = [3,4]
#X = []
#Y = 0
#
#for N in L:
#	X.append(N * N)
#	Y += N * N
#print X
#print Y


a = 0
b = 0
c = 0

x = 100 # sum of a+b+c




















